[package]
name = "bfcompiler"
version = "1.0.0"
edition = "2021"

[dependencies]
anyhow = "1.0.98"
clap = { version = "4.5.36", features = ["derive"] }
colored = "3.0.0"
thiserror = "2.0.12"
tempfile = "3.19.1"
